# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60d857b7762081d6e0e4ee3ebf133909f6808d67f977fc3ed306cab6a8d82b98ba6e6c8b3f54b0a5ef3c2c984660f4e4f54712b21498c447b8b6dfbd4c115775

test:
  secret_key_base: 94e527d2c08a1358f8f638a9e3345fceddf30ea97aecfecefc24af993c687341f2e7d74edf0147a51f7f43b0a80a6799ccae4261d99d3ebeff6d0b8264c3a3d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
